### ISSUE TITLE
Not compiling on Ubuntu 22.04

### ISSUE THREAD

**Issue by nowatbuer** [corneal64/Realtek-USB-Wireless-Adapter-Drivers#22]
Hello 
,tried to install thos one on the current Ubuntu version, but it fails with:

sudo dkms install rtl8188fu/1.0
...
Error! Bad return status for module build on kernel: 5.15.0-33-generic (x86_64)
/var/lib/dkms/rtl8188fu/1.0/build/make.log shows: 

/var/lib/dkms/rtl8188fu/1.0/build/core/rtw_br_ext.c:25:10: fatal error: net/ipx.h: Datei oder Verzeichnis nicht gefunden
   25 | #include <net/ipx.h>

**Comment by jhonathannc** [comment]
This worked for me.

```
sudo apt update
sudo apt install git
git clone https://github.com/kelebek333/rtl8188fu
sudo apt install dkms
sudo dkms add ./rtl8188fu
sudo dkms build rtl8188fu/1.0
sudo dkms install rtl8188fu/1.0
sudo cp ./rtl8188fu/firmware/rtl8188fufw.bin /lib/firmware/rtlwifi/
reboot
```

Font: [Install 0bda:f179 Realtek Semiconductor Corp. (rtl8188fu), or Netgear rtl8812au USB WiFi adapters](https://askubuntu.com/questions/1197223/install-0bdaf179-realtek-semiconductor-corp-rtl8188fu-or-netgear-rtl8812au)
